---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-secret-store
spec:
  provider:
    azurekv:
      tenantId: "123123"
      vaultUrl: "https://azure.awesome.id.microsoft.com/blabla"
      authSecretRef:
        clientId:
          name: azure-kv-access
          key: client-app-id
          namespace: external-secrets
        clientSecret:
          name: azure-kv-access
          key: client-app-secret
          namespace: external-secrets