victoria-metrics-operator:
  createCRD: true
  replicaCount: 1
  logLevel: "info"
  rbac:
    create: true
    pspEnabled: true
  operator:
    disable_prometheus_converter: 
    prometheus_converter_add_argocd_ignore_annotations: 
    psp_auto_creation_enabled: 
    enable_converter_ownership: 
    useCustomConfigReloader: 
  serviceAccount:
    create: true
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    #-- available env variables found here: https://docs.victoriametrics.com/operator/vars.html
    - name: VM_VMALERTDEFAULT_CONFIGRELOADIMAGE
      value: ghcr.io/jimmidyson/configmap-reload:v0.11.0
    - name: VM_VMAGENTDEFAULT_CONFIGRELOADIMAGE
      value: ghcr.io/prometheus-operator/prometheus-config-reloader:v0.64.1
    - name: VM_VMALERTMANAGER_CONFIGRELOADERIMAGE
      value: ghcr.io/jimmidyson/configmap-reload:v0.11.0
  serviceMonitor:
    enabled: true