services:
  defaultStorageClass: "kubernetes-storage-policy"
  defaultServiceUri: "my.kubernetes.cluster.net"
  coreServices:
    dns:
      externaldns:
        powerdnsApiKey: "testing123"
        domainFilter:
          - uri: "*.subdomain.corp.local"
          - uri: "*.sub.corp.local"
        txtOwnerId: "testTxtOwnerId"
        apiUrl: "localhost"
        apiPort: "1234"
        imageRegistry: "hub.docker.com"
        corporateCertificateConfigmapName: "corp-ca"
    networking:
      nginxIngress:
        controllerImageRepository: "registry.k8s.io/ingress-nginx/controller"
        admissionWebhooksImageRepository: "registry.k8s.io/ingress-nginx/kube-webhook-certgen"
        defaultBackendImageRepository: "registry.k8s.io/defaultbackend-amd64"
    observability:
      prometheusNodeExporter:
        imageRegistry: "quay.io"
        imageRepository: "prometheus/node-exporter"
    security:
      certManager:
        privilegedPspName: "psp:system-privileged"
        dnsRecursiveNameserverIp: "127.0.0.1:53"
        acmeHttpResolverImage: "quay.io/jetstack/cert-manager-acmesolver:v1.9.1"
        imageRepository: "quay.io/jetstack/cert-manager-controller"
        webhookImageRepository: "quay.io/jetstack/cert-manager-webhook"
        cainjectImageRepository: "quay.io/jetstack/cert-manager-cainjector"
        startupipcheckImageRepository: "quay.io/jetstack/cert-manager-ctl"
    system: {}