observability:
  victoriaMetricsOperator:
    createCRD: true
    replicaCount: 1
    rbac:
      create: true
      enabled: true
    serviceAccount: true
    operator:
      disablePrometheusConverter: false
      prometheusConverterAddArgocdIgnoreAnnotations: true
      pspAutoCreationEnabled: true
      enableConverterOwnership: false
      useCustomConfigReloader: false
    resources:
      cpuLimit: 300
      memoryLimit: 512
      cpuRequest: 100
      memoryRequest: 256
    environment:
      vmVmalertdefaultConfigreloadimage: "ghcr.io/jimmidyson/configmap-reload:v0.11.0"
      vmVmagentdefaultConfigreloadimage: "ghcr.io/prometheus-operator/prometheus-config-reloader:v0.64.1"
      vmVmalertmanagerConfigreloadimage: "ghcr.io/jimmidyson/configmap-reload:v0.11.0"
    serviceMonitor: true
  victoriaMetricsCluster:
    defaults:
      enabled: true
    replicationFactor: 2
    vmstorage:
      replicaCount: 3
      storageSize: 10
      resources:
        cpuLimit: 2000
        memoryLimit: 2048
    vmselect:
      replicaCount: 3
      storageSize: 5
      resources:
        cpuLimit: 1000
        memoryLimit: 1024
    vminsert:
      replicaCount: 4
      resources:
        cpuLimit: 1000
        memoryLimit: 512
  victoriaMetricsAgent:
    defaults:
      enabled: true
    imageRepository: "victoriametrics/vmagent"
    remoteWriteUrl: "http://victoria-metrics-cluster-vminsert.default:8480/insert/0/prometheus"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      clusterIusser: "prod"
      commonName: "metrics-agent.my.awesome.cluster.tld"
  victoriaMetricsAlert:
    defaults:
      enabled: true
    imageRepository: "victoriametrics/vmagent"
    remoteReadUrl: "http://victoria-metrics-cluster-vmselect.default:8481/select/0/prometheus"
    remoteWriteUrl: "http://victoria-metrics-cluster-vminsert.default:8480/insert/0/prometheus"
    notifiersUrl: "http://vmalertmanager-alertmanager.victoria-metrics:9093/"
    datasourceUrl: "http://victoria-metrics-cluster-vmselect.default:8481/select/0/prometheus"
    