observability:
  victoriaMetricsOperator:
    createCRD: true
    replicaCount: 1
    rbac:
      create: true
      enabled: true
    serviceAccount: true
    resources:
      cpuLimit: 300
      memoryLimit: 512
      cpuRequest: 100
      memoryRequest: 256
    environment:
      vmVmalertdefaultConfigreloadimage: "ghcr.io/jimmidyson/configmap-reload:v0.11.0"
      vmVmagentdefaultConfigreloadimage: "ghcr.io/prometheus-operator/prometheus-config-reloader:v0.64.1"
      vmVmalertmanagerConfigreloadimage: "ghcr.io/jimmidyson/configmap-reload:v0.11.0"
    serviceMonitor: true
  victoriaMetricsCluster:
    defaults:
      enabled: true
    replicationFactor: 2
    vmstorage:
      replicaCount: 3
      storageSize: 10
      resources:
        cpuLimit: 2000
        memoryLimit: 2048
    vmselect:
      replicaCount: 3
      storageSize: 5
      resources:
        cpuLimit: 1000
        memoryLimit: 1024
    vminsert:
      replicaCount: 4
      resources:
        cpuLimit: 1000
        memoryLimit: 512