psp:
  privileged: psp:system-privileged

cert-manager:
  extraArgs:
    - --dns01-recursive-nameservers=127.0.0.1:53
    - --dns01-recursive-nameservers-only
    - --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.9.1
  image:
    repository: quay.io/jetstack/cert-manager-controller
  webhook:
    image:
      repository: quay.io/jetstack/cert-manager-webhook
  cainjector:
    image:
      repository: quay.io/jetstack/cert-manager-cainjector
  startupapicheck:
    image:
      repository: quay.io/jetstack/cert-manager-ctl